**Import NumPy Library as np**

In [1]:
import numpy as np

**Create an Array of 15 zeros**

In [2]:
np.zeros(15)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

**Create an array of 10 ones**

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

**Create an array of 10 fives**

In [7]:
np.ones(10) * 5


array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

**Create an array of the integers from 10 to 70**

In [8]:
np.arange(10,71)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70])

**Create an array of all the even integers from 10 to 50**

In [11]:
np.arange(10,71,2)


array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70])

**Create an array of all the odd integers from 10 to 50**

In [12]:
np.arange(11, 71, 2)

array([11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43,
       45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69])

**Create a 4x4 matrix with values ranging from 0 to 8**

In [13]:
np.arange(16).reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

**Create a 4x4 identity matrix**

In [68]:
#The eye() method of Python numpy class returns a 2-D array with ones on the diagonal and zeros elsewhere.

p.eye(4,4, k=0)


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

**Use NumPy to generate a 5 random number between 0 and 3**

In [61]:
#randint(low, high=None, size=None, dtype='l')
#Return random integers from `low` (inclusive) to `high` (exclusive).

np.random.randint(4,size=5)

array([0, 0, 0, 0, 3])

**Use NumPy to generate a random number between 0 and 1**

In [64]:
#rand(d0, d1, ..., dn)
#Random values in a given shape.

np.random.rand(1)

array([0.77650573])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [69]:
np.random.randn(25)

array([ 1.50236097, -0.99587149,  0.69196344, -0.65419581,  1.15944969,
       -1.12728682,  1.13831937,  0.84617311,  2.48159666,  0.63931283,
       -0.10488875, -0.33905136,  0.71030507, -0.02886932, -0.83152208,
       -0.63013669, -1.45698232, -0.54906954, -0.72543428, -0.70611821,
        0.29954124, -1.78178446, -0.60611409,  0.1830103 ,  1.41185329])

In [70]:
np.arange(1,101).reshape(10,10) / 100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

**Create an array of 20 linearly spaced points between 0 and 1:**


In [73]:
np.linspace(0,1,30)

array([0.        , 0.03448276, 0.06896552, 0.10344828, 0.13793103,
       0.17241379, 0.20689655, 0.24137931, 0.27586207, 0.31034483,
       0.34482759, 0.37931034, 0.4137931 , 0.44827586, 0.48275862,
       0.51724138, 0.55172414, 0.5862069 , 0.62068966, 0.65517241,
       0.68965517, 0.72413793, 0.75862069, 0.79310345, 0.82758621,
       0.86206897, 0.89655172, 0.93103448, 0.96551724, 1.        ])

##  Numpy Indexing and Selection


In [74]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [76]:
#Grab  array 8,  9, 10, 13, 14, 15,18, 19, 20, 23, 24, 25
#mat[y,x] = grab all start from [1] y axes and grab all star from [2]

mat[1:,2:]

array([[ 8,  9, 10],
       [13, 14, 15],
       [18, 19, 20],
       [23, 24, 25]])

In [78]:
#Grab  array 12

mat[2,1]

12

In [91]:
#Grab  array 8, 13, 18
mat[1:4,2:3]

array([[ 8],
       [13],
       [18]])

In [96]:
#Grab array 16, 17, 18, 19, 20
mat[3,:]

array([16, 17, 18, 19, 20])

In [98]:
#Grab Array 16, 17, 18, 19, 20, 21, 22, 23, 24, 25
mat[3:5,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [99]:
#Get the sum of all the values in mat
mat.sum()

325

In [100]:
#Get the standard deviation of the values in mat
mat.std()

7.211102550927978

In [103]:
#Get the sum of all the columns in mat
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

In [104]:
#Get the sum of all the columns in mat
mat.sum(axis=1)

array([ 15,  40,  65,  90, 115])